version: '3.9'  # version 3.9 or later is required for profiles
services:
  redis:
    image: redis
    environment:
      - REDIS_USERNAME=dm
    ports:
      - "6379:6379"
    profiles:
      - db
      - app
  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    profiles:
      - db
      - app
  app:
    build:
      context: .
      args:
        GIT_USERNAME: ${GIT_USERNAME}
        GIT_TOKEN: ${GIT_TOKEN}
    ports:
      - "443:8080"
    environment:
      - JWT_SECRET_TOKEN=${JWT_SECRET_TOKEN}
      - REDIS_USERNAME=dm
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - GHCR_TOKEN=${GHCR_TOKEN}
      - CERT_PATH=${CERT_PATH}
      - CERT_KEY_PATH=${CERT_KEY_PATH}
    depends_on:
      - postgres
      - redis
    profiles:
      - app
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app
    profiles:
      - app