version: '3.9'  # version 3.9 or later is required for profiles
services:
  redis:
    image: redis
    environment:
      - REDIS_USERNAME=dm
    ports:
      - "6379:6379"
    profiles:
      - db
      - app
      - remote-app
  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    profiles:
      - db
      - app
      - remote-app
  remote-app:
    image: ghcr.io/ztkent/data-manager/data-manager:0.0.1
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET_TOKEN=${JWT_SECRET_TOKEN}
      - REDIS_HOST=${REDIS_DOCKER_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_DOCKER_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - GHCR_TOKEN=${GHCR_TOKEN}
    depends_on:
      - postgres
      - redis
    profiles:
      - remote-app
  app:
    build:
      context: .
      args:
        GIT_USERNAME: ${GIT_USERNAME}
        GIT_TOKEN: ${GIT_TOKEN}
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET_TOKEN=${JWT_SECRET_TOKEN}
      - REDIS_HOST=${REDIS_DOCKER_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_DOCKER_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - GHCR_TOKEN=${GHCR_TOKEN}
    depends_on:
      - postgres
      - redis
    profiles:
      - app