version: '3'
services:
  redis:
    image: redis
    environment:
      - REDIS_USERNAME=dm
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"